### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by chmac** [syntax-tree/unist-util-remove-position#4]
Would be great to have typescript types. I know there's a lot of packages in the queue, so sharing what's working for me right now in case it's helpful to anybody else.

```typescript
declare module 'unist-util-remove-position' {
  import { Node } from 'unist';
  const removePosition: <T extends Node>(node: T, force?: boolean) => T;
  export default removePosition;
}
```

I've got that in my `module.d.ts` file. Don't have time to create a proper PR with types and tests right now.

**Comment by wooorm** [comment]
Released in 3.0.0!
